# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
# Generated by scripts/sync-design.py.
ACTION_ICON_SIZE=14
COPY_FEEDBACK_MS=1500
ACTION_LABELS={'copy': 'Kopieren', 'edit': 'Bearbeiten', 'branch': 'In neuem Chat verzweigen'}
